### ISSUE TITLE
Sort changes by numerical value

### ISSUE THREAD

**Issue by cyb70289** [conbench/conbench#109] opened 2021-07-15 02:17 UTC
In below snapshot, I sort `change` column in increasing order. But 28% is listed before 3%, it's sorted by string, not numeric.

![conbench](https://user-images.githubusercontent.com/4149843/125717486-caec8729-1013-4fe3-a759-d9faa1ccee3e.png)

**Comment by dianaclarke** [comment] 2021-07-15 19:57
I think I know what the issue is. Sorting appears to work fine until there is a `---` (means unknown) value in the list. I'll see if making unknowns blank instead preserves the correct sorting.

**Comment by dianaclarke** [comment] 2021-07-15 20:17
Fixed in: https://github.com/ursacomputing/conbench/commit/93f999b901889d68f2f489d519126a31d490a745

Before:

<img width="1198" alt="Screen Shot 2021-07-15 at 1 58 35 PM" src="https://user-images.githubusercontent.com/878798/125851837-3f0614fb-632e-4f21-b55e-3758dc968729.png">

After:

<img width="1181" alt="Screen Shot 2021-07-15 at 2 15 02 PM" src="https://user-images.githubusercontent.com/878798/125851857-a883c43d-18a6-4c9b-b396-75298cd22fc8.png">

Thanks for taking the time to report this @cyb70289!!

**Closed as completed by dianaclarke** 2021-07-15 20:17 UTC
